GET http://127.0.0.1:5000/users/
Accept: application/json
Authorization: Bearer

###

POST http://127.0.0.1:5000/users/
Accept: application/json
Content-Type: application/json
Authorization: Bearer

{
  "username": "Armen",
  "password": "test",
  "role": "admin"
}

###

DELETE http://127.0.0.1:5000/users/4
Content-Type: application/json
Authorization: Bearer

###