GET http://127.0.0.1:5000/users/
Accept: application/json

###

POST http://127.0.0.1:5000/users/
Accept: application/json
Content-Type: application/json

{
  "username": "Armen",
  "password": "test",
  "role": "admin"
}

###

DELETE http://127.0.0.1:5000/users/4
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IkFybWVuIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjU2NzA0OTg2fQ.ZCPXpiIkzkJQUINo8qUNZ5ZFoPkZuwTg3RmSLXkoKJY

###